---
- name: Install package
  yum: name={{item}} state=latest
  with_items:
    - libselinux-python
    - java-1.8.0-openjdk-devel

- name: Ensure download directory exists
  file: path={{zk_download_dir}} state=directory

- name: Ensure lib directory exists
  file: path={{zk_lib_dir}} state=directory recurse=yes

- name: Download zookeeper version.
  get_url: url={{zk_archive_url}} dest={{zk_download_dir}}/{{zk_archive}}

- name: Extract zookeeper archive
  unarchive: src={{zk_download_dir}}/{{zk_archive}} dest={{zk_lib_dir}}

#- name: Write myid file.
#  template: src=myid.j2 dest={{zk_data_dir}}/myid owner=zookeeper group=zookeeper
#
#- name: Write log4j conf file.
#  template: src=log4j.properties dest={{zookeeper_conf_dir}}/log4j.properties owner=zookeeper group=zookeeper
#
#- name: Configure zookeeper
#  template: src=zoo.cfg.j2 dest={{zookeeper_conf_dir}}/zoo.cfg owner=zookeeper group=zookeeper
#
#- name: Start zookeeper
#  service: name=zookeeper-server enabled=yes state=restarted
