---
- hosts: all
  vars:
    zookeeper_client_port: '2181'
  roles:
    - common
    - ntp-client
    - scala
    - conda
    - { role: zookeeper, when: "'masters' in group_names" }
    - mesos
    - docker
    - hdfs
    - spark
