---
- name: create admin group
  group: name=admin state=present

- name: add user
  user: name={{username}}
        state=present
        groups={{grouplist}}
        generate_ssh_key=yes
        ssh_key_bits=2048
        ssh_key_comment={{username}}@{{ansible_hostname}}
        ssh_key_passphrase=
        ssh_key_type=rsa
  ignore_errors: yes

- name: add user
  user: name={{username}}
        state=present
        generate_ssh_key=yes
        ssh_key_bits=2048
        ssh_key_comment={{username}}@{{ansible_hostname}}
        ssh_key_passphrase=
        ssh_key_type=rsa
  when: ansible_hostname == 'localhost' or
        ansible_hostname == 'firewall'

- name: admin group must have passwordless sudo rights
  lineinfile: "dest=/etc/sudoers
              state=present
              regexp='^%admin'
              line='%admin          ALL=(ALL)       NOPASSWD: ALL'
              insertafter='^# %wheel'
              validate='visudo -cf %s'"

- name: fetch newly deployed key
  fetch: src=/home/{{username}}/.ssh/id_rsa.pub
         dest=/home/{{username}}/.ssh/
         validate_checksum=no

- name: add all ssh keys
  authorized_key:
    user={{username}}
    key="{{ lookup('file', '/home/' + username + '/.ssh/' + item + '/home/' + username + '/.ssh/id_rsa.pub') }}"
  with_items: "{{groups['all']}}"

- name: deploy local ssh key
  authorized_key: user={{username}}
                  key="{{ lookup('file', '/home/' + username + '/.ssh/id_rsa.pub') }}"

- name: deploy anaconda path
  blockinfile:
    dest: "/home/{{username}}/.bashrc"
    block: "export PATH={{anaconda_target_path}}/bin:$PATH"
    state: present
