---
- name: Add sbt repository
  yum_repository:
    name: bintray-sbt
    description: SBT RPM package from Bintray
    file: bintray--sbt-rpm.repo
    baseurl: http://dl.bintray.com/sbt/rpm
    gpgcheck: no
    enabled: yes

- name: Ensure sbt presence
  yum: name=sbt state=latest

- name: Create scala lib dir
  file: path={{scala_lib_path_target}} state=directory recurse=yes

- name: Download scala v{{scala_version}}
  get_url: url={{scala_download_url}}
    dest=/opt/src/{{scala_binary_file}}

- name: Ensure binary is installed
  yum: name=/opt/src/{{scala_binary_file}} state=present
