---
  # Download conf
spark_version: 2.1.0
spark_download_dir: /opt/src
spark_url: "{{mirror_base_url}}/spark"
spark_version_name: spark-{{spark_version}}-bin-hadoop2.7
spark_archive_file: "{{spark_version_name}}.tgz"
spark_download_url: "{{spark_url}}/spark-{{spark_version}}/{{spark_archive_file}}"
spark_md5: 50E73F255F9BDE50789AD5BD657C7A71

# Install conf
spark_lib_dir: "/usr/local/lib"
spark_conf_dir: "/etc/spark"
spark_target: "{{spark_lib_dir}}/{{spark_version_name}}"
spark_home: "{{spark_lib_dir}}/spark"
spark_bin_dir: "/usr/local/bin"
spark_workdir: "/var/lib/spark"

# Spark-env conf
hadoop_conf_dir: /etc/hadoop
mesos_master: mesos://zk://{{ groups.masters | join(':' + zookeeper_client_port + ',')  }}:{{ zookeeper_client_port  }}/mesos
mesos_lib: /usr/local/lib/mesos/lib/libmesos.so

# History server
history_hostname: "{{hostvars[groups['masters'][2]]['inventory_hostname']}}"

spark_log_dir: /var/log/spark
spark_run_dir: /var/run/spark
spark_tmp_dirs:
  - /tmp
# Here you should add a list of directory on different devices like :
# - /data/disk1/spill
# - /data/disk2/spill
# - /data/disk3/spill
