###
- name: ntpd package installed
  yum: name=ntp state=latest

- name: chrony package removed
  yum: name=chrony state=absent

- name: setup configuration file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  when: is_offline == True

- name: launch ntpd service
  service: name=ntpd state=restarted enabled=yes
