###
- name: ntpd package installed
  yum: name=ntp state=latest

- name: chrony package removed
  yum: name=chrony state=absent

- name: setup configuration file
  lineinfile:
    dest: /etc/ntp.conf
    line: 'server {{ntp_server}} iburst'
  when: is_offline == True

- name: launch ntpd service
  service: name=ntpd state=restarted enabled=yes
