###
- name: ntp must not be there
  yum: name=ntp state=absent

- name: install chrony daemon
  yum: name=chrony state=latest

- name: setup configuration file
  template: src=chrony.conf.j2 dest=/etc/chrony.conf

- name: launch chronyd service
  service: name=chronyd state=restarted enabled=yes
